In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df_athletes = pd.read_json('../dataset/olympic_athletes.json')
df_athletes.head()

,athlete_url,athlete_full_name,games_participations,first_game,athlete_year_birth,athlete_medals,bio
0,https://olympics.com/en/athletes/cooper-woods-...,Cooper WOODS-TOPALOVIC,1,Beijing 2022,2000.0,NaN,NaN
1,https://olympics.com/en/athletes/elofsson,Felix ELOFSSON,2,PyeongChang 2018,1995.0,NaN,NaN
2,https://olympics.com/en/athletes/dylan-walczyk,Dylan WALCZYK,1,Beijing 2022,1993.0,NaN,NaN
3,https://olympics.com/en/athletes/olli-penttala,Olli PENTTALA,1,Beijing 2022,1995.0,NaN,NaN
4,https://olympics.com/en/athletes/reikherd,Dmitriy REIKHERD,1,Beijing 2022,1989.0,NaN,NaN

In [36]:
print(df_athletes.shape)
print(df_athletes.dtypes)
df_athletes.isnull().sum()

(75904, 7)
athlete_url                 str
athlete_full_name           str
games_participations      int64
first_game                  str
athlete_year_birth      float64
athlete_medals              str
bio                         str
dtype: object

athlete_url                 0
athlete_full_name           0
games_participations        0
first_game                 22
athlete_year_birth       2456
athlete_medals          60552
bio                     53062
dtype: int64

In [37]:
percent_missing = df_athletes.isnull().sum() * 100 / len(df_athletes)
print(percent_missing.sort_values(ascending=False))

athlete_medals          79.774452
bio                     69.906724
athlete_year_birth       3.235666
first_game               0.028984
athlete_url              0.000000
athlete_full_name        0.000000
games_participations     0.000000
dtype: float64

In [39]:
# supprimer colonnes
df_athletes = df_athletes.drop(['athlete_medals', 'bio'], axis=1)

KeyError: "['athlete_medals', 'bio'] not found in axis"

In [33]:
# Remplire na
df_athletes['athlete_year_birth'] = df_athletes['athlete_year_birth'].fillna(df_athletes['athlete_year_birth'].median())

df_athletes['first_game'] = df_athletes['first_game'].fillna(df_athletes['first_game'].mode()[0])

In [47]:
df_athletes.head()

,athlete_url,athlete_full_name,games_participations,first_game,athlete_year_birth
0,https://olympics.com/en/athletes/cooper-woods-...,Cooper WOODS-TOPALOVIC,1,Beijing 2022,2000.0
1,https://olympics.com/en/athletes/elofsson,Felix ELOFSSON,2,PyeongChang 2018,1995.0
2,https://olympics.com/en/athletes/dylan-walczyk,Dylan WALCZYK,1,Beijing 2022,1993.0
3,https://olympics.com/en/athletes/olli-penttala,Olli PENTTALA,1,Beijing 2022,1995.0
4,https://olympics.com/en/athletes/reikherd,Dmitriy REIKHERD,1,Beijing 2022,1989.0

In [41]:
df_hosts = pd.read_xml('../dataset/olympic_hosts.xml')
df_hosts.head()

,index,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,0,beijing-2022,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
1,1,tokyo-2020,2021-08-08T14:00:00Z,2021-07-23T11:00:00Z,Japan,Tokyo 2020,Summer,2020
2,2,pyeongchang-2018,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,PyeongChang 2018,Winter,2018
3,3,rio-2016,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,Rio 2016,Summer,2016
4,4,sochi-2014,2014-02-23T16:00:00Z,2014-02-07T04:00:00Z,Russian Federation,Sochi 2014,Winter,2014

In [42]:
print(df_hosts.shape)
print(df_hosts.dtypes)
df_hosts.isnull().sum()

(53, 8)
index              int64
game_slug            str
game_end_date        str
game_start_date      str
game_location        str
game_name            str
game_season          str
game_year          int64
dtype: object

index              0
game_slug          0
game_end_date      0
game_start_date    0
game_location      0
game_name          0
game_season        0
game_year          0
dtype: int64

In [50]:
df_medals = pd.read_excel('../dataset/olympic_medals.xlsx')
df_medals.head()

,Unnamed: 0,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA
1,1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA
2,2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR
3,3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR
4,4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE

In [45]:
print(df_medals.shape)
print(df_medals.dtypes)
df_medals.isnull().sum()

(21697, 13)
Unnamed: 0               int64
discipline_title           str
slug_game                  str
event_title                str
event_gender               str
medal_type                 str
participant_type           str
participant_title          str
athlete_url                str
athlete_full_name          str
country_name               str
country_code               str
country_3_letter_code      str
dtype: object

Unnamed: 0                   0
discipline_title             0
slug_game                    0
event_title                  0
event_gender                 0
medal_type                   0
participant_type             0
participant_title        15113
athlete_url               4670
athlete_full_name         3624
country_name                 0
country_code              1502
country_3_letter_code        0
dtype: int64

In [48]:
percent_missing = df_medals.isnull().sum() * 100 / len(df_medals)
print(percent_missing.sort_values(ascending=False))

participant_title        69.654791
athlete_url              21.523713
athlete_full_name        16.702770
country_code              6.922616
Unnamed: 0                0.000000
discipline_title          0.000000
slug_game                 0.000000
event_title               0.000000
event_gender              0.000000
medal_type                0.000000
participant_type          0.000000
country_name              0.000000
country_3_letter_code     0.000000
dtype: float64

In [51]:
# Regarde les lignes GameTeam avec et sans URL
gameteam = df_medals[df_medals['participant_type'] == 'GameTeam']
print(gameteam['athlete_url'].isnull().sum())
print(gameteam['athlete_url'].notnull().sum())

3782
2802

In [52]:
mask = df_medals['athlete_url'].isnull()
print(df_medals[mask]['participant_type'].value_counts())

participant_type
GameTeam    3782
Athlete      888
Name: count, dtype: int64

In [27]:
df_results = pd.read_html('../dataset/olympic_results.html')[0]
print(df_results.shape)
print(df_results.dtypes)
# df_results.isnull().sum()
percent_missing = df_results.isnull().sum() * 100 / len(df_results)
print(percent_missing.sort_values(ascending=False))

(162804, 16)
Unnamed: 0                int64
discipline_title            str
event_title                 str
slug_game                   str
participant_type            str
medal_type                  str
athletes                    str
rank_equal               object
rank_position               str
country_name                str
country_code                str
country_3_letter_code       str
athlete_url                 str
athlete_full_name           str
value_unit                  str
value_type                  str
dtype: object
athletes                 95.100857
medal_type               87.588757
rank_equal               80.021375
value_unit               51.692833
value_type               44.688705
athlete_url              20.154910
athlete_full_name        12.995995
country_code              3.093290
rank_position             2.382005
Unnamed: 0                0.000000
discipline_title          0.000000
event_title               0.000000
slug_game                 0.000000
participant_type          0.000000
country_name              0.000000
country_3_letter_code     0.000000
dtype: float64